# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38ddd629e5f95e4b447a2f37e29c0afe96ba8f7f77839b3ff22563ee047b9f4dd2811aa93469b7d98213dd5dbcf8609507d7712b5ccd2182d760fb708a7ef6d0

test:
  secret_key_base: 0a03d4d5e5d0ec75cd0aaa8b6c6a4811c1e5eac5739112f720bb6394b7c6b36f02480e7a547fc8cb2e4f8dab0c33db3efd73e8445888a6c7a417896167182eb3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
